// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQ77IBDRiORocAltu46zzUlOaQXhCxSM',
    appId: '1:333564535358:web:3712101aa88a3a1de3a76f',
    messagingSenderId: '333564535358',
    projectId: 'rotinakids-2a9ff',
    authDomain: 'rotinakids-2a9ff.firebaseapp.com',
    storageBucket: 'rotinakids-2a9ff.firebasestorage.app',
    measurementId: 'G-EM6YTHTREG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEzQpAmwNTM7dp6UzQ3_U1vu4xxBJ34oY',
    appId: '1:333564535358:android:6eafcc3476342814e3a76f',
    messagingSenderId: '333564535358',
    projectId: 'rotinakids-2a9ff',
    storageBucket: 'rotinakids-2a9ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1v0iBDubfTt0oCABXLZnc7DhMnMEc6YY',
    appId: '1:333564535358:ios:279fee1c9ac46052e3a76f',
    messagingSenderId: '333564535358',
    projectId: 'rotinakids-2a9ff',
    storageBucket: 'rotinakids-2a9ff.firebasestorage.app',
    iosBundleId: 'com.example.kidsRoutineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1v0iBDubfTt0oCABXLZnc7DhMnMEc6YY',
    appId: '1:333564535358:ios:638226edf2606784e3a76f',
    messagingSenderId: '333564535358',
    projectId: 'rotinakids-2a9ff',
    storageBucket: 'rotinakids-2a9ff.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLQ77IBDRiORocAltu46zzUlOaQXhCxSM',
    appId: '1:333564535358:web:29db0879cc002956e3a76f',
    messagingSenderId: '333564535358',
    projectId: 'rotinakids-2a9ff',
    authDomain: 'rotinakids-2a9ff.firebaseapp.com',
    storageBucket: 'rotinakids-2a9ff.firebasestorage.app',
    measurementId: 'G-84J63MKS21',
  );
}
